### ISSUE TITLE
a problem about coefficient

### ISSUE THREAD

**Issue by csufangyu** [ShivinDass/inverse_rl#1]
line 178 in the file"inverse_rl/Paper1_Implementation/lp_discrete_gridworld/LinearProgrammingGridWorldSmallStates.py " :
        c[25:2 * 25] = -1
it is coefficient (P_a1-P_a)（I-gamma*P_a1）^{-1}，and why is it -1?in the line 173:                
 `                condition= - np.dot(trans_probs[i, :, optimalAction] - trans_probs[i, :, j], tempInverse)`,,its coefficient have been set "-1"?
thanks very much!

**Comment by ShivinDass** [comment]
Hey, take a look at the scipy.optimize.linprog library which is being used to solve the LP formed. It can only minimize the objective function. 
Since we need to maximize and not minimize, we make c[25: 2*25] equal to -1 to make the solver minimize the negative value, i.e. maximize our actual objective. 

Similarly, in the library, constraints are of the form A_ub @ x **<=** b_ub whereas we need them of the form A_ub @ x **>=** b_ub, hence we again multiply the variables with -1 to get the desired behavior.

**Comment by csufangyu** [comment]
good！ thanks very much！-------- 原始邮件 --------发件人： ShivinDass <notifications@github.com>日期： 2020年4月15日周三 凌晨1:52收件人： ShivinDass/inverse_rl <inverse_rl@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [ShivinDass/inverse_rl] a problem about coefficient (#1)
Hey, take a look at the scipy.optimize.linprog library which is being used to solve the LP formed. It can only minimize the objective function.
Since we need to maximize and not minimize, we make c[25: 2*25] equal to -1 to make the solver minimize the negative value, i.e. maximize our actual objective.
Similarly, in the library, constraints are of the form A_ub @ x <= b_ub whereas we need them of the form A_ub @ x >= b_ub, hence we again multiply the variables with -1 to get the desired behavior.
